### ISSUE TITLE
lcobucci/jwt Missing

### ISSUE THREAD

**Issue by jochemh** [wieni/mercure#1]
Dear,

After installing the module and trying to imply it within a custom service I get the following error.

`You cannot use "Symfony\Component\Mercure\Token\LcobucciFactory" as the "lcobucci/jwt" package is not installed` 

I've installed the 'lcobucci/jwt' package with the following command "composer require lcobucci/jwt", however the error remains.
Any idea's what i might be doing wrong?

PHP 7.4 and Drupal 9.

Best regards,
Jochem

**Comment by jochemh** [comment]
No `composer dump-autoload`  doesn't resolve anything unfortunately, neither does `drush cr`.
The 'lcobucci/jwt' library is added in the vendor folder and also included in composer :s and other modules do seem to work with the auto loader...

**Comment by DieterHolvoet** [comment]
Maybe it's an issue with your local development environment? Can you try to restart whatever it is you're using? (vagrant, lando, docker, ddev, ...)
