### ISSUE TITLE
Drupal coding standards

### ISSUE THREAD

**Issue by a-mawlawi** [wieni/mercure#3]
Thank you for this awesome module.

I really respect your own coding standards, but as this is a Drupal module we should go with Drupal coding standards without the need to run coding-standards script via composer and include the dev plugins.

If you are welcoming this, I will be happy to create a pull request for this.

Regards,

**Comment by RobinHoutevelts** [comment]
Not our own coding standard. But PSR-12 like almost any other PHP project.

Although I respect Drupal's coding standard. Drupal should use PSR-12

**Comment by a-mawlawi** [comment]
No need to create a pull request then, Thanks for saving my time.

**Comment by RobinHoutevelts** [comment]
@a-mawlawi you'll be happy to know I changed my mind and moved the project over to https://www.drupal.org/project/mercure where @DieterHolvoet is co-maintainer 🥳 

---

If, by now, you forked this project and have any contributions/issues you would like to share, please do!

The preferred channel is https://www.drupal.org/project/issues/mercure

I apologise for closing this issue earlier.
